### PR TITLE
chore(README): fix typo

### PR DESCRIPTION
**Pull request by midopooler**
__Which issue does this PR address?__
`chore(README): fix typo`

Closes # NA

__Acceptance Criteria__

* [x] Corresponds to the concept 
* [x] Corresponds to the design 

__Definition of Done__

* [x] corresponds to [the design principles](https://github.com/bpmn-io/design-principles)
* [x] corresponds to [the code standards](https://github.com/bpmn-io/.github/blob/master/.github/CONTRIBUTING.md#creating-a-pull-request)
* [x] passes Continuous Integration checks
* [x] available as feature branch on GitHub
  * [x] contains the cleaned up commit history
  * [x] commit messages satisfy our [commit message guidelines](https://www.conventionalcommits.org/)
  * [x] a single commit closes the issue via Closes #issuenr

### CODE REVIEW

**Comment by pinussilvestrus** [comment]
Thanks for your contribution. Please update the commit message to fit [our guidelines](https://www.conventionalcommits.org/).

> chore(README): fix typo

**Comment by midopooler** [comment]
UPDATED

**Comment by pinussilvestrus** [comment]
No, you didn't

https://github.com/bpmn-io/awesome-bpmn-io/pull/10/commits

image

**Comment by pinussilvestrus** [comment]
Nice try opening the same PR twice, cf. https://github.com/bpmn-io/awesome-bpmn-io/pull/11

In case you participate in the Hacktoberfest, please take a look at our open issues and try to make a _meaningful_ contribution

**Comment by midopooler** [comment]
@pinussilvestrus I'm sorry for this PR and will be doing a meaningful one for sure. 
For a favour, could you please remove the invalid tag or either delete this PR from your end?

**Comment by pinussilvestrus** [comment]
> For a favor, could you please remove the invalid tag or either delete this PR from your end?

why that?

**Comment by philippfromme** [comment]
> For a favour, could you please remove the invalid tag or either delete this PR from your end?

No. Good luck with getting your free t-shirt.

**Pull request closed without merging**
